### PR TITLE
Feature/mongodb

### PR DESCRIPTION
**Pull request by AymenSakouhi**
From https://github.com/AymenSakouhi/realEstate/issues/14
I seperated backend and frontend and worked on adding backend to post and list newsletters.
@Selimgss feel free to spot the differences and learn the backend part.

### CODE REVIEW

**Review by Selimgss — COMMENTED** [review]
error


error running npm start

**Comment by AymenSakouhi** [comment]
@Selimgss You are trying to do an `npm run start` at the wrong directory. 
You should enter frontend folder and do that. 
Right now we have both front and back, one start with the usual npm run start : frontend, and the second folder you need to cd into it and do `npm run dev` but you don't need to for now.

**Review by Selimgss — COMMENTED** [review]
How did you test your code?

**Comment by AymenSakouhi** [comment]
I JUST WROTE YOU ABOVE EXACTLY WHAT I DID.
you will have two folders and you can test via `npm run start` in frontend folder
and `npm run dev` when you do the backend folder.
Also you might install postman to help you do the api request testing.

**Pull request merged**
